const loadingText = document.querySelector('.loading-text'); // selects loading-text class from the HTML
const bg = document.querySelector('.bg'); // selects bg class from HTML
const para = document.querySelector('.para'); // selects para class form HTML
const result = document.querySelector('.result');

let load = 0; // loading number countdown

let interval = setInterval(Blur, 25) // calls custom Blur function every 25ms, as time is passed in ms in setInterval
// the unique id that is generated by setInterval is stored in interval variable 
function Blur() {
    load++;
    if (load > 99) {
        clearInterval(interval); // clears the interval after reaching 100
    }
    loadingText.innerHTML = `${load}%`; // chnages the loading numbers from 0 to 100%
    loadingText.style.opacity = scale(load, 0, 100, 1, 0);
    bg.style.filter = `blur(${scale(load, 0, 100, 30, 0)}px)`;
    para.style.opacity = scale(load, 0, 100, 1, 0);
    //after the load reaches 100, following twxt appears
    if (load > 99) {
        result.innerHTML = "Town Night Winter";
    }
}

const scale = (num, in_min, in_max, out_min, out_max) => {
    return (num - in_min) * (out_max - out_min) / (in_max - in_min) + out_min;
};
